# Generated by Django 4.1.13 on 2024-12-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0007_alter_measurement_calves_alter_measurement_chest_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='measurement',
            table='measurements',
        ),
    ]
