# Generated by Django 4.1.13 on 2024-12-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0008_alter_measurement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='measurement',
            table='measurements_measurement',
        ),
    ]
